---
- name: Setup apache web server
  hosts: all
  become: yes

  tasks:
  - name: Install HTTPD
    yum:
      name: httpd
      state: present
    #become: yes

  - name: Start HTTPD
    service:
      name: httpd
      state: started
  
  - name: Enable HTTPD
    service:
      name: httpd
      enabled: true
...
