
---
- name: Setup apache web server
  hosts: n5
  become: yes

  tasks:
  - name: Install Apache2
    apt:
      name: apache2
      state: present
   
  - name: Start apache2
    apt:
      name: apache2
      state: started
  
  - name: Enable apache2
    apt:
      name: apache2
      enabled: true

    

...
