---
- name: Setup apache web server
  hosts: all
  become: yes

  tasks:
  - name: Install HTTPD on Amazon
    dnf:
      name: httpd
      state: present
    when: ansible_distribution == "Amazon" 
 
  - name: Install HTTPD on CentOS
    yum:
      name: httpd
      state: present
    when: ansible_distribution == "CentOS" 

  - name: Start HTTPD
    service:
      name: httpd
      state: started
    when: ansible_distribution == "CentOS" or ansible_distribution == "Amazon"

  - name: Enable HTTPD
    service:
      name: httpd
      enabled: true
    when: ansible_distribution == "CentOS" or ansible_distribution == "Amazon"

  - name: Install Apache2 on Ubuntu
    apt:
      name: apache2
      state: present
    when: ansible_distribution == "Ubuntu"

  - name: Install Apache2 on Debian
    apt:
      name: apache2
      state: present
    when: ansible_distribution == "Debian"

  - name: Start apache2
    service:
      name: apache2
      state: started
    when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

  - name: Enable apache2
    service:
      name: apache2
      enabled: true
    when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
...   
