#copy the os.html from master to apropriate nodes with their names
#scp

---

- name: Setup apache web server
  hosts: all
  become: yes

  tasks:
  - name: copy on CentOS
    copy:
      src: os.html
      dest: /var/www/html/centos.html
    when: ansible_distribution == "CentOS"

  - name: copy on Amazon
    copy:
      src: os.html
      dest: /var/www/html/amazon.html
    when: ansible_distribution == "Amazon"

  - name: copy on Ubuntu
    copy:
      src: os.html
      dest: /var/www/html/ubuntu.html
    when: ansible_distribution == "Ubuntu"
...   
