#copy the os.html from master to apropriate nodes with their names
#scp

---

- name: Setup apache web server
  hosts: n4
  become: yes

  tasks:
  - name: copy date app
    copy:
      src: date.php
      dest: /var/www/html/date.php
    when: ansible_distribution == "CentOS"

  - name: Install PHP
    yum:
      name: php
      state: present
    when: ansible_distribution == "CentOS"

  - name: Restart HTTPD
    service:
      name: httpd
      state: restarted
    when: ansible_distribution == "CentOS"

    
...   
